// <auto-generated />
using DBApiTutorial.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DBApiTutorial.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20230714152111_ApiTutorialMigration2")]
    partial class ApiTutorialMigration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DBApiTutorial.Domain.Entity.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Robert",
                            IsDeleted = false,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Pamela",
                            IsDeleted = false,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "John",
                            IsDeleted = false,
                            LastName = "Franklin"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Kathy",
                            IsDeleted = false,
                            LastName = "McDonald"
                        });
                });

            modelBuilder.Entity("DBApiTutorial.Domain.Entity.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("RegionId")
                        .IsUnique();

                    b.ToTable("Offices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Baton Rouge",
                            IsDeleted = false,
                            Phone = "555-222-2222",
                            RegionId = 1,
                            State = ""
                        },
                        new
                        {
                            Id = 2,
                            City = "Port Allen",
                            IsDeleted = false,
                            Phone = "555-123-4567",
                            RegionId = 2,
                            State = ""
                        },
                        new
                        {
                            Id = 3,
                            City = "Gonzales",
                            IsDeleted = false,
                            Phone = "555-777-7777",
                            RegionId = 3,
                            State = ""
                        },
                        new
                        {
                            Id = 4,
                            City = "Plaquemine",
                            IsDeleted = false,
                            Phone = "555-444-4444",
                            RegionId = 4,
                            State = ""
                        });
                });

            modelBuilder.Entity("DBApiTutorial.Domain.Entity.OfficeEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OfficeId");

                    b.ToTable("OfficeEmployees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            IsDeleted = false,
                            OfficeId = 1
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 1,
                            IsDeleted = false,
                            OfficeId = 2
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 2,
                            IsDeleted = false,
                            OfficeId = 2
                        },
                        new
                        {
                            Id = 4,
                            EmployeeId = 3,
                            IsDeleted = false,
                            OfficeId = 3
                        },
                        new
                        {
                            Id = 5,
                            EmployeeId = 3,
                            IsDeleted = false,
                            OfficeId = 4
                        },
                        new
                        {
                            Id = 6,
                            EmployeeId = 4,
                            IsDeleted = false,
                            OfficeId = 4
                        });
                });

            modelBuilder.Entity("DBApiTutorial.Domain.Entity.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RegionNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "East Baton Rouge",
                            RegionNumber = ""
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "West Baton Rouge",
                            RegionNumber = ""
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Ascension",
                            RegionNumber = ""
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Iberville",
                            RegionNumber = ""
                        });
                });

            modelBuilder.Entity("DBApiTutorial.Domain.Entity.Office", b =>
                {
                    b.HasOne("DBApiTutorial.Domain.Entity.Region", null)
                        .WithOne()
                        .HasForeignKey("DBApiTutorial.Domain.Entity.Office", "RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DBApiTutorial.Domain.Entity.OfficeEmployee", b =>
                {
                    b.HasOne("DBApiTutorial.Domain.Entity.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBApiTutorial.Domain.Entity.Office", null)
                        .WithMany()
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
